version: "3.1"
services: 
  www:
    container_name: www_container
    build:
      context: .
      dockerfile: Dockerfile-PHP
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./app:/var/www/
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:vNWHSHdpGSQ4ylaG81ONT/YKqLpi8EpHm/2Ri8148ac=
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=postgresql_db
      - DB_PORT=5432
      - DB_DATABASE=gotour
      - DB_USERNAME=root
      - DB_PASSWORD=senha
    networks:
      - php_mysql_network
  mysql_db:
    container_name: mysql_container
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=senha
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./dados_compartilhados:/home 
    networks:
      - php_mysql_network
  postgresql_db:
    container_name: postgresql_container
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=senha
    volumes:
      - ./dados_postgresql:/var/lib/postgresql/
      - ./dados_compartilhados:/home 
    networks:
      - php_mysql_network
networks:
  php_mysql_network: